run:
  mode: "rlvr"

grpo:
  num_generations: 4
  
  max_prompt_length: 1024
  max_completion_length: 512
  
  temperature: 0.7

  use_vllm: false

data:
  type: "rlvr_math"
  source: "hf"
  max_prompt_len: 1024
  num_proc: 8

training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4

wandb:
  tags: ["rlvr", "grpo", "math"]
